#!/bin/bash

set -e

TARGET_DIR="$HOME/bin"
if [ -z "$TRAVIS" ]; then
  TARGET_DIR=/usr/local/bin
fi

mkdir -p $TARGET_DIR
curl -OL https://github.com/google/protobuf/releases/download/v3.4.0/protoc-3.4.0-linux-x86_64.zip
unzip protoc-3.4.0-linux-x86_64.zip -d protoc3
mv protoc3/bin/* $TARGET_DIR && chmod -R 775 $TARGET_DIR
# mv protoc3/include/* /usr/local/include && chmod -R 755 /usr/local/include

# remove the garbage
rm protoc-3.4.0-linux-x86_64.zip && \
rm -rf protoc3
